sudo: false
language: node_js
node_js:
  - '4'
  - '0.12'
  - '0.10'
script: "npm run-script coveralls"

# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
